GradExam/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GradExam.Models;
using GradExam.Services;
using Microsoft.AspNetCore.Authorization;
using GradExam.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GradExam.Controllers
{
	/// <summary>
		/// Controller for handling the various operations on a course
		/// </summary>
		/// <returns></returns>
    [Authorize(Roles = "Admin,Director")]
    public class CourseController : Controller
    {
        private IGradeExamRepository context;
		/// <summary>
		/// Parameterized constructor for building a connection to IGradeExamRepository
		/// </summary>
		/// <returns></returns>
        public CourseController(IGradeExamRepository context)
        {
            this.context = context;
        }	
		/// <summary>
		/// IAction method for returning a delete view
		/// </summary>
		/// <param name="id">Id for a course</param>
		/// <returns></returns>
        public IActionResult Delete(int id)
        {
            var course = context.ReadCourse(id);
            if (course == null)
            {
                return RedirectToAction("Index");
            }
            return View(course);
        }
		/// <summary>
		/// IAction method for posting the results of an delete
		/// </summary>
		/// <param name="id">Id for a course</param>
		/// <returns></returns>
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            context.DeleteCourse(id);
            return RedirectToAction("Index");
        }
		/// <summary>
		/// IAction method for creating the displays for students outcomes and answers along with detailing a course
		/// </summary>
		/// <param name="id">Id for a course</param>
		/// <returns></returns>
         public IActionResult Details(int id)
        {
            var listAllStudents = context.ReadAllStudents().ToList();
            var listAllOutcomes = context.ReadAllOutcomes().ToList();
            var listAllQuesAnswers = context.ReadAllQuesAnswers().ToList();

            var listStudents = new List<Student>();
            var listLearnOutcomes = new List<LearnOutcome>();
            var listQuesAnswers = new List<QuesAnswer>();

            var studentsInCourse = new List<Student>();
            foreach(var item in context.ReadCourse(id).StudentCourses)
            {
                studentsInCourse.Add(item.Student);
            }

            foreach(var student in listAllStudents)
            {
                if(!studentsInCourse.Contains(student))
                {
                    listStudents.Add(student);
                }
            }

            var learnOutcomeForCourse = new List<LearnOutcome>();
            foreach (var item in context.ReadCourse(id).LearnOutcomes)
            {
                learnOutcomeForCourse.Add(item);
            }

            foreach (var lo in listAllOutcomes)
            {
                if (!learnOutcomeForCourse.Contains(lo))
                {
                    listLearnOutcomes.Add(lo);
                }
            }

            var quesAnswerForCourse = new List<QuesAnswer>();
            foreach (var item in context.ReadCourse(id).QuesAnswers)
            {
                quesAnswerForCourse.Add(item);
            }

            foreach (var qa in listAllQuesAnswers)
            {
                if (!quesAnswerForCourse.Contains(qa))
                {
                    listQuesAnswers.Add(qa);
                }
            }

            ViewBag.Students = listStudents;
            ViewBag.LearningOutcomes = listLearnOutcomes;
            ViewBag.QuesAnswers = listQuesAnswers;

            var course = context.ReadCourse(id);
            if (course == null)
            {
                return RedirectToAction("Index");
            }
            return View(course);
        }
		/// <summary>
		/// IAction method for returning the view of an add to course
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <returns></returns>
        [Authorize(Roles = "Admin, Instructor")]
        public IActionResult Add()
        {
            // Get the list of Users
            var listInstructors = new List<User>();
            listInstructors = context.ReadAllUsers().ToList();

            ViewBag.Instructors = listInstructors;

            return View();
        }
		/// <summary>
		/// IAction method for posting the results of an add, handles validation
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <returns></returns>
        [HttpPost]
        public IActionResult Add(EditCourseViewModel vm)
        {

            if (ModelState.IsValid)
            {
                vm.Course.Instructor = context.Read(vm.UserId);
                context.AddCourse(vm.Course);
                return RedirectToAction("Index");
            }
            return View(vm);

        }
		/// <summary>
		/// IAction method for returning an index view
		/// </summary>
		/// <returns></returns>
		public IActionResult Index()
		{
            IEnumerable<Course> courses = context.ReadAllCourses();

			return View(courses);
		}
		/// <summary>
		/// IAction method for returning a course edit view
		/// </summary>
		/// <param name="id">Id for a course</param>
		/// <returns></returns>
        public IActionResult Edit(int id)
        {

            // Get the list of Users
            var listInstructors = new List<User>();
            listInstructors = context.ReadAllUsers().ToList();

            ViewBag.Instructors = listInstructors;

            var course = context.ReadCourse(id);
            if (course == null)
            {
                return RedirectToAction("Index");
            }

            var vm = new EditCourseViewModel()
            {
                Course = course,
                UserId = course.Instructor.Id

            };

            return View(vm);
        }
		/// <summary>
		/// IAction method for posting a course edit view, handles validation
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <returns></returns>
        [HttpPost]
        public IActionResult Edit(EditCourseViewModel vm)
        {
            if (ModelState.IsValid)
            {
                vm.Course.Instructor = context.Read(vm.UserId);
                context.UpdateCourse(vm.Course.Id, vm.Course);
                return RedirectToAction("Index");
            }
            return View(vm);
        }
		/// <summary>
		/// IAction method for returning a student addition to a course
		/// </summary>
		/// <param name="studentId">Id for a student</param>
		/// <param name="courseId">Id for a course</param>
		/// <returns></returns>
        public IActionResult AddStudent(int studentId, int courseId)
        {
            try
            {
                if (!ModelState.IsValid || studentId == 0)
                {
                    return RedirectToAction("Details", new { id = courseId });
                }

                var student = context.ReadStudent(studentId);
                var course = context.ReadCourse(courseId);
                context.AddStudentToACourse(student, course);
            }
            catch(Exception ex)
            {
                return Content(ex.ToString());
            }

            return RedirectToAction("Details", new { id = courseId });
        }
		/// <summary>
		/// IAction method for removing a student from a course
		/// </summary>
		/// <param name="studentId">Id for a student</param>
		/// <param name="courseId">Id for a course</param>
		/// <returns></returns>
        public IActionResult RemoveStudent(int studentId, int courseId)
        {
            try
            {
                var student = context.ReadStudent(studentId);
                var course = context.ReadCourse(courseId);
                context.RemoveStudentFromACourse(student, course);
            }
            catch (Exception ex)
            {
                return Content(ex.ToString());
            }

            return RedirectToAction("Details", new { id = courseId });
        }
		/// <summary>
		/// IAction method for adding a learning outcome to a course
		/// </summary>
		/// <param name="courseId">Id for a concentration</param>
		/// <param name="learnOutcomeId">Id for a learning outcome</param>
		/// <returns></returns>
        public IActionResult AddLearningOutcome(int learningOutcomeId, int courseId)
        {
            try
            {
                if(!ModelState.IsValid || learningOutcomeId == 0)
                {
                    return RedirectToAction("Details", new { id = courseId });
                }

                var lo = context.ReadOutcome(learningOutcomeId);
                var course = context.ReadCourse(courseId);
                context.AddLOToACourse(lo, course);
            }
            catch (Exception ex)
            {
                return Content(ex.ToString());
            }

            return RedirectToAction("Details", new { id = courseId });
        }
		/// <summary>
		/// IAction method for removing a learning outcome
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <returns></returns>
        public IActionResult RemoveLearningOutcome(int learningOutcomeId, int courseId)
        {
            try
            {
                var lo = context.ReadOutcome(learningOutcomeId);
                var course = context.ReadCourse(courseId);
                context.RemoveLOFromACourse(lo, course);
            }
            catch (Exception ex)
            {
                return Content(ex.ToString());
            }

            return RedirectToAction("Details", new { id = courseId });
        }
		/// <summary>
		/// IAction method for adding a question to a course
		/// </summary>
		/// <param name="courseid">Id for a question answer</param>
		/// <param name="questionAnswerid">Id for a course</param>
		/// <returns></returns>

GradExam/Views/Report/Add.cshtml
@model GradExam.ViewModels.EditCourseViewModel
@{
    ViewData["Title"] = "Add";
}
@using Microsoft.AspNetCore.Identity

@inject UserManager<User> UserManager

<h2>Add</h2>
@using (Html.BeginForm("Add", "Course"))
{
    @Html.ValidationSummary()
    <div class="col-sm-4">
        <div class="form-group">
            @Html.LabelFor(model => model.Course.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Course.Name, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Course.Semester, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Course.Semester, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Course.Section, new { htmlAttributes = new { @class = "form-control" } })
            @Html.EditorFor(model => model.Course.Section, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Course.Instructor, new { htmlAttributes = new { @class = "form-control" } })
            @{ if (User.IsInRole("Instuctor"))
                {
                    @Html.DropDownListFor(model => model.UserId, new SelectList(@ViewBag.Instructors, "Id", "FullName"), "--- Instructors ---", new { @class = "form-control" })
                }
                else
                {
                    @Html.DropDownListFor(model => model.UserId, new SelectList(@ViewBag.Instructors, "Id", "FullName"), "--- Instructors ---", new { @class = "form-control" })
                }
            }
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Course.Concentration, new { htmlAttributes = new { @class = "form-control" } })
            <br />
            <select id="myList">
                <option value="1">Applied Computer Science</option>
                <option value="2">Information Technology</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
}

GradExam/Views/Report/Delete.cshtml
@model GradExam.Models.Course

@{
    ViewData["Title"] = $"Delete Course: {Model.Name}";
}

<h2>@ViewData["Title"]</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Semester)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Semester)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Section)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Section)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Instructor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Instructor)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index" asp-controller="Home">Back to List</a>
    </form>
</div>

GradExam/Views/Report/Details.cshtml
@model GradExam.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h2>@Html.DisplayFor(model => model.Name) - @Html.DisplayFor(model => model.Semester)</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Section)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Section)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Instructor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Instructor.FullName)
        </dd>
        <dt>@Html.DisplayNameFor(model => model.Concentration)</dt>
        <dd>@Html.DisplayFor(model => model.Concentration)</dd>
    </dl>
    <div class="row">
        <div class="col-lg-4">
            <table class="table">
                <thead>
                    <tr>
                        <th>Student</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.StudentCourses)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(model => item.Student.Name)
                            </td>
                            <td><a style="color:blue;" href="/Course/RemoveStudent/?studentId=@item.StudentId&courseId=@item.CourseId">Remove</a></td>
                        </tr>
                    }
                </tbody>
            </table>
            @using (Html.BeginForm("AddStudent", "Course"))
            {
                @Html.Hidden("courseId", Model.Id)
                <div class="form-group">
                    <div class="col-xs-8">
                        @Html.DropDownList("studentId", new SelectList(ViewBag.Students, "Id", "Name"), "--- Students ---", new { @class = "form-control" })
                    </div>
                    <div class="col-xs-4">
                        <input type="submit" value="Add Student" class="btn btn-default" />
                    </div>
                </div>
            }
        </div>

        <!-- For the learning outcomes -->
        <div class="col-lg-4">
            <table class="table">
                <thead>
                    <tr>
                        <th>Learning Outcome</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @*------ Put Learning outcomes here -------*@
                    @foreach (var item in Model.LearnOutcomes)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(model => item.LearningOutcome)
                            </td>
                            <td><a style="color:blue;" href="/Course/RemoveStudent/?learningOutcomeId=@item.Id&courseId=@Model.Id">Remove</a></td>
                        </tr>
                    }

                </tbody>
            </table>
            @using (Html.BeginForm("AddLearningOutcome", "Course"))
            {
                @Html.Hidden("courseId", Model.Id)
                <div class="form-group">
                    <div class="col-xs-8">
                        @Html.DropDownList("learningOutcomeId", new SelectList(ViewBag.LearningOutcomes, "Id", "LearningOutcome"), "--- Learning Outcomes ---", new { @class = "form-control" })
                    </div>
                    <div class="col-xs-4">
                        <input type="submit" value="Add Outcome" class="btn btn-default" />
                    </div>
                </div>
            }
        </div>

        <!-- For the Q & A -->
        <div class="col-lg-4">
            <table class="table">
                <thead>
                    <tr>
                        <th>Question</th>
                        <th>Answer</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model.QuesAnswers)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(model => item.Question)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Answer)
                        </td>
                        <td><a style="color:blue;" href="/Course/RemoveQuestionAnswer/?questionAnswerId=@item.Id&courseId=@Model.Id">Remove</a></td>
                    </tr>
                    }

                </tbody>
            </table>
            @using (Html.BeginForm("AddQuestionAnswer", "Course"))
            {
                @Html.Hidden("courseId", Model.Id)
                <div class="form-group"> 
                    <div class="col-xs-8">
                        @Html.DropDownList("questionAnswerId", new SelectList(ViewBag.QuesAnswers, "Id", "Question", "Answer"), "--- Question Answer ---", new { @class = "form-control" })
                    </div>
                    <div class="col-xs-4">
                        <input type="submit" value="Add Q/A" class="btn btn-default" />
                    </div>
                </div>
            }
        </div>
    </div>

</div>


<div class="form-group">
    <br/>
    <a asp-action="Index">Back to List</a>
</div>

GradExam/Views/Report/Edit.cshtml
@model GradExam.ViewModels.EditCourseViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Course.Id" type="hidden" />
            <div class="form-group">
                <label asp-for="Course.Name" class="control-label"></label>
                <input asp-for="Course.Name" class="form-control" />
                <span asp-validation-for="Course.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course.Semester" class="control-label"></label>
                <input asp-for="Course.Semester" class="form-control" />
                <span asp-validation-for="Course.Semester" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course.Section" class="control-label"></label>
                <input asp-for="Course.Section" class="form-control" />
                <span asp-validation-for="Course.Section" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course.Instructor" class="control-label"></label>
                @Html.DropDownListFor(model => model.UserId, new SelectList(@ViewBag.Instructors, "Id", "FullName"), "--- Instructors ---", new { @class = "form-control" })
                <span asp-validation-for="Course.Instructor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GradExam/Views/Report/Index.cshtml
@model IEnumerable<GradExam.Models.Course>
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<p>
    <a asp-action="Add">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Id)</th>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.Semester)</th>
            <th>@Html.DisplayNameFor(model => model.Section)</th>
            <th>@Html.DisplayNameFor(model => model.Instructor)</th>
            <th>@Html.DisplayNameFor(model => model.Concentration)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            if (item.Name == null)
            {

            }
            else
            {
                <tr>
                    <td>@Html.DisplayFor(model => item.Id)</td>
                    <td>@Html.DisplayFor(model => item.Name)</td>
                    <td>@Html.DisplayFor(model => item.Semester)</td>
                    <td>@Html.DisplayFor(model => item.Section)</td>
                    <td>@Html.DisplayFor(model => item.Instructor.FullName)</td>
                    <td>@Html.DisplayFor(model => item.Concentration.Name)</td>
                    <td>

                        <a href="/Course/Edit/@item.Id">Edit |</a>
                        <a href="/Course/Details/@item.Id">Details |</a>
                        <a href="/Course/Delete/@item.Id">Delete</a>
                    </td>
                </tr>

            }
        }
    </tbody>
</table>