GradExam/Models/User.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GradExam.Models
{
    public class User : IdentityUser
    {
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }

        public string FullName
        {
            get { return this.FirstName + " " + this.LastName; }
        }

        public override string ToString()
        {
            return this.FirstName + " " + this.LastName;
        }
    }
}

GradExam/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GradExam.Models;
using GradExam.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GradExam.Controllers
{	/// <summary>
		/// Controller for handling various user functions
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <returns></returns>
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private IGradeExamRepository context;
		/// <summary>
		/// Constructor for creating a connection to IGradeExamRepository
		/// </summary>
		/// <param name="context">connection to IGradeExamRepository</param>
		/// <returns></returns>
        public UserController(IGradeExamRepository context)
        {
            this.context = context;
        }
		/// <summary>
		/// IAction method for returning an index view
		/// </summary>
		/// <returns></returns>
        public IActionResult Index()
        {
            var model = context.ReadAllUsers();
            return View(model);
        }
		/// <summary>
		/// IAction method for returning a Create view
		/// </summary>
		/// <returns></returns>
        public IActionResult Create()
        {
            return View();
		}
		/// <summary>
		/// IAction method for posting details of the creation of a user
		/// </summary>
		/// <param name="User">User to be created</param>
		/// <returns></returns>
        [HttpPost]
        public IActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                context.CreateUser(user);
                return RedirectToAction("Index");
            }
            return View(user);
        }
		/// <summary>
		/// IAction method for returning an edit view
		/// </summary>
		/// <param name="id">Id for a user</param>
		/// <returns></returns>
        public IActionResult Edit(string id)
        {
            var model = context.Read(id);

            return View(model);
        }
		/// <summary>
		/// IAction method for posting details about an update to a user 
		/// </summary>
		/// <param name="id">Id for a concentration</param>
		/// <param name="user">User that is being updated</param>
		/// <returns></returns>
        [HttpPost]
        public IActionResult Edit(int id, User user)
        {
            if(!ModelState.IsValid)
            {
                return RedirectToAction("Edit", id);
            }

            context.Update(id, user);
            return RedirectToAction("Index");
        }

        
    }
}

GradExam/Views/User/Edit.cshtml
@model GradExam.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h2>@Model.FirstName @Model.LastName</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

GradExam/Views/User/Index.cshtml
@model IEnumerable<GradExam.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "User", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>